### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ayyneya** [maxicc/owrpc#1]
Did everything the way it said (and yes I'm not very smart with these things). 
This is what I get: 

[!] Error! Couldn't import a module. Did you download the dependencies?
[!] Check https://git.io/owrpc and make sure, then try running again.

**Comment by maxicc** [comment]
Hi there!

Looks like you need to install the dependencies required to make owrpc work. Please try running `pip install pypresence` in your terminal application, then let me know if it works.

If not, please let me know which version of Python you’re running and what operating system you’re on.

Thanks!

**Comment by ayyneya** [comment]
I completely missed the install requests command, woops.
Fixed now, thank you.

**Comment by maxicc** [comment]
Not your fault, it was in the requirements file but I hadn't added it to the documentation yet so it wasn't obvious that it needed to be done. Thanks for reminding me to, hope you like owrpc :+1:
